d = {
    'news': {
        0: {'tag': 'news', 'ico': 'reddit', 'name': 'r/News', 'title': 'r/news', 'url': 'https://www.reddit.com/r/news/.rss'},
        1: {'tag': 'news', 'ico': 'guardian', 'name': 'Guard', 'title': 'Guardian', 'url': 'https://www.theguardian.com/world/rss'},
        3: {'tag': 'news', 'ico': 'sfgate', 'name': 'SF', 'title': 'SF Gate', 'url': 'https://www.sfgate.com/bayarea/feed/Bay-Area-News-429.php'},
        4: {'tag': 'news', 'ico': 'truthdig', 'name': 'Truth Dig', 'title': 'TruthDig', 'url': 'https://www.truthdig.com/feed/'},
        5: {'tag': 'news', 'ico': 'muse', 'name': 'Muse', 'title': 'Muse', 'url': 'https://muse.mu/rss/gigs'},
        6: {'tag': 'news', 'ico': 'reddit', 'name': 'r/Sci', 'title': 'r/science', 'url': 'https://www.reddit.com/r/science/.rss'},
    },
    'tech': {
        30: {'tag': 'tech', 'ico': 'hackernews', 'name': 'Hackr News', 'title': 'hacker news', 'url': 'https://news.ycombinator.com/rss'},
        31: {'tag': 'tech', 'ico': 'techmeme', 'name': 'Tech Meme',
             'title': 'Tech Meme', 'url': 'https://www.techmeme.com/feed.xml?x=1'},
        32: {'tag': 'tech', 'ico': 'arstechnica','name': 'Ars Tech', 'title': 'Ars Technica', 'url': 'http://feeds.arstechnica.com/arstechnica/index'},
        33: {'tag': 'tech', 'ico': 'techcrunch','name': 'Tech Crnch', 'title': 'Tech Crunch', 'url': 'https://techcrunch.com/feed/'},
        34: {'tag': 'tech',  'ico': 'reddit', 'name': 'r/Tech', 'title': 'r/technology', 'url': 'https://www.reddit.com/r/technology/.rss'},
        35: {'tag': 'tech', 'ico': 'slashdot', 'name': 'Slash Dot',
             'title': 'slashdot', 'url': 'http://rss.slashdot.org/Slashdot/slashdotMain/to'},
        36: {'tag': 'tech', 'ico': 'newspaper', 'name': 'The Infor',
             'title': 'The Information', 'url': 'https://www.theinformation.com/feed'},
        37: {'tag': 'tech', 'ico': 'wired', 'name': 'Wired',
             'title': 'Wired', 'url': 'https://www.wired.com/feed/rss'},
        38: {'tag': 'tech', 'ico': 'mit', 'name': 'MIT Tech',
             'title': 'MIT Tech Review', 'url': 'https://www.technologyreview.com/stories.rss'},
        39: {'tag': 'tech', 'ico': 'readwrite', 'name': 'Read Write',
             'title': 'Read Write', 'url': 'https://readwrite.com/feed/?x=1'}  
    },
    'security': {
        80: {'tag': 'security', 'ico': 'newspaper', 'name': 'Sec Blvd',
             'title': 'Sec Boulevard', 'url': 'https://securityboulevard.com/feed/'},
        81: {'tag': 'security', 'ico': 'krebs', 'name': 'Krebs',
             'title': 'Krebs on Security', 'url': 'https://krebsonsecurity.com/feed/'},
        82: {'tag': 'security', 'ico': 'securityweekly', 'name': 'Sec Weekly',
             'title': 'Sec Weekly', 'url': 'http://feeds.feedburner.com/securityweekly/XBIC'},
        83: {'tag': 'security', 'ico': 'securityledger', 'name': 'Security Ledger',
             'title': 'Security Ledger', 'url': 'https://feeds.feedblitz.com/thesecurityledger'},
        84: {'tag': 'security', 'ico': 'twitter', 'url': "https://twitrss.me/twitter_user_to_rss/?user=schneierblog", 'name': "Sch", 'title': "Bruce Schneier"},
        85: {'tag': 'security', 'ico': 'twitter', 'url': "https://twitrss.me/twitter_user_to_rss/?user=DarkReading", 'name': "DR", 'title': "Dark Reading"},
        86: {'tag': 'security', 'ico': 'twitter', 'url': "https://twitrss.me/twitter_user_to_rss/?user=troyhunt", 'name': "TH", 'title': "Troy Hunt"},
        87: {'tag': 'security', 'ico': 'twitter', 'url': "https://twitrss.me/twitter_user_to_rss/?user=mikko", 'name': "Mi", 'title': "Mikko Hypponen"},
        88: {'tag': 'security', 'ico': 'twitter', 'url': "https://twitrss.me/twitter_user_to_rss/?user=briankrebs", 'name': "BK", 'title': "Brian Krebs"},
    },
    'econ': {
        100: {'tag': 'econ', 'ico': 'nakedcapitalism', 'name': 'Naked Capit', 'title': 'Naked Capitalism', 'url': 'https://www.nakedcapitalism.com/feed'},
        101: {'tag': 'econ', 'ico': 'michaelhudson', 'name': 'Michl Hudsn', 'title': 'Michael Hudson', 'url': 'http://michael-hudson.com/feed/'},
        102: {'tag': 'news', 'ico': 'renegade', 'name': 'Rene', 'title': 'Renegade Inc', 'url': 'https://renegadeinc.wpengine.com/feed/'},
        103: {'tag': 'econ', 'ico': 'maxkeiser', 'name': 'MK', 'title': 'Max Keiser', 'url': 'https://www.maxkeiser.com/feed/'},
        104: {'tag': 'econ', 'ico': 'twitter', 'url': "https://twitrss.me/twitter_user_to_rss/?user=mkblyth", 'name': "Mark Blyth", 'title': "mkblyth"},
        105: {'tag': 'econ', 'ico': 'twitter', 'url': "https://twitrss.me/twitter_user_to_rss/?user=zerohedge", 'name': "Zero Hedge", 'title': "zerohedge"},
        106: {'tag': 'econ', 'ico': 'twitter', 'url': "https://twitrss.me/twitter_user_to_rss/?user=chrismartenson", 'name': "Peak Prosp", 'title': "peakprosperity"},
        107: {'tag': 'econ', 'ico': 'newspaper', 'url': "https://wolfstreet.com/feed/", 'name': "Wolf Street", 'title': "Wolf Street"},
        108: {'tag': 'econ', 'ico': 'newspaper', 'url': "https://riggedgame.blog/feed/", 'name': "Rigged Game", 'title': "Rigged Game"},
    },
    'code': {
        40: {'tag': 'code', 'ico': 'reddit', 'name': 'r/Prog',
            'title': 'r/programming', 'url': 'https://www.reddit.com/r/programming/.rss'},
        41: {'tag': 'code', 'ico': 'reddit', 'name': 'r/DIB', 'title': 'r/data', 'url': 'https://www.reddit.com/r/dataisbeautiful/.rss'},
        42: {'tag': 'code', 'ico': 'reddit', 'name': 'r/Code', 'title': 'r/code', 'url': 'https://www.reddit.com/r/code/.rss'},
        43: {'tag': 'code', 'ico': 'newspaper', 'name': 'Crazy Progr', 'title': 'Crazy Programmer', 'url': 'http://www.thecrazyprogrammer.com/feed'},
        44: {'tag': 'code', 'ico': 'reddit', 'name': 'r/Pyth', 'title': 'r/python', 'url': 'https://www.reddit.com/r/Python/.rss'},
        45: {'tag': 'code', 'ico': 'reddit', 'name': 'r/JS', 'title': 'r/javascript', 'url': 'https://www.reddit.com/r/JavaScript/.rss'},
        46: {'tag': 'code', 'ico': 'reddit', 'name': 'r/DSci', 'title': 'r/datascience', 'url': 'https://www.reddit.com/r/datascience/.rss'},
        47: {'tag': 'code', 'ico': 'newspaper', 'name': 'Real Pyth',
            'title': 'Real Python', 'url': 'https://realpython.com/atom.xml?format=xml'},
        48: {'tag': 'code', 'ico': 'newspaper', 'name': 'David Walsh',
            'title': 'David Walsh', 'url': 'https://davidwalsh.name/feed'},
    },
    'life': {
        51: {'tag': 'life', 'ico': 'reddit', 'name': 'r/ELI',
            'title': 'r/explainlikeimfive', 'url': 'https://www.reddit.com/r/explainlikeimfive/.rss'},
        52: {'tag': 'life',  'ico': 'reddit','name': 'r/Frug', 'title': 'r/frugal', 'url': 'https://www.reddit.com/r/frugal/.rss'},
        53: {'tag': 'life',  'ico': 'makeuseof', 'name': 'Make UseOf', 'title': 'make use of', 'url': 'https://www.makeuseof.com/feed/'},
        54: {'tag': 'life',  'ico': 'reddit', 'name': 'r/DNo', 'title': 'r/digitalnomad', 'url': 'https://www.reddit.com/r/digitalnomad/.rss'},
        55: {'tag': 'life',  'ico': 'reddit', 'name': 'r/TIL', 'title': 'r/todayilearned', 'url': 'https://www.reddit.com/r/todayilearned/.rss'},
        56: {'tag': 'life',  'ico': 'teamblind', 'name': 'Blind /All', 'title': 'blind/all',  'url': "https://www.teamblind.com/rss/All/rss"},
        57: {'tag': 'life', 'ico': 'twitter', 'url': "https://twitrss.me/twitter_user_to_rss/?user=slickdeals", 'name': "Slick Deals", 'title': "Slick Deals"},
        58: {'tag': 'life', 'ico': 'twitter', 'url': "https://twitrss.me/twitter_user_to_rss/?user=hip2save", 'name': "Save",
            'title': "Hip2Save"},
    },
    'health': {
        70: {'tag': 'health', 'ico': 'twitter', 'url': "https://twitrss.me/twitter_user_to_rss/?user=foundmyfitness", 'name': "Rhonda Patrick", 'title': "Dr Rhonda Patrick"},
        71: {'tag': 'health', 'ico': 'twitter', 'url': "https://twitrss.me/twitter_user_to_rss/?user=drjasonfung", 'name': "Jason Fung", 'title': "Dr Jason Fung"},
        72: {'tag': 'health', 'ico': 'twitter', 'url': "https://twitrss.me/twitter_user_to_rss/?user=SatchinPanda", 'name': "Satchin Panda",
            'title': "Satchin Panda"},
        73: {'tag': 'health', 'ico': 'twitter', 'url': "https://twitrss.me/twitter_user_to_rss/?user=davidsinclair", 'name': "David Sinclair",
            'title': "David Sinclair"},
        74: {'tag': 'health', 'ico': 'newspaper', 'url': "http://feeds.feedburner.com/bulletproofexec", 'name': "Dave Asprey",
            'title': "Dave Asprey"},
        75: {'tag': 'health', 'ico': 'newspaper', 'url': "https://blog.daveasprey.com/category/podcasts/feed/", 'name': "Asprey Podcast",
            'title': "Asprey Podcast"},
    },
    'trends': {
        60: {'tag': 'trends', 'ico': 'trends', 'name': 'Tr', 'title': 'Google Trends', 'url': 'https://trends.google.com/trends/hottrends/atom/hourly'},
    },
}
